services:
  - type: web
    name: callofmine-file-host
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disk:
      name: uploads-disk
      mountPath: /var/data
      sizeGB: 10
    envVars:
      - key: STORAGE_PROVIDER
        value: local
      - key: UPLOAD_DIR
        value: /var/data/uploads
